### PR TITLE
Move to content entities

### PR DESCRIPTION
**Pull request by chrfritsch**

### CODE REVIEW

**Comment by Greg-Boggs** [comment]
Thanks! I will review it this week.

**Comment by chrfritsch** [comment]
Hi Greg, whats the current status?

**Comment by Greg-Boggs** [comment]
It's on my list this week, bit delayed finding time to contribute. But, I'll get this up shortly.

**Comment by Greg-Boggs** [comment]
The following extensions will be enabled: alinks
Do you really want to continue? (y/n): y

Error: Class 'Drupal\alinks\KeywordHtmlRouteProvider' not found in /Users/gregboggs/Sites/drupal8/core/lib/Drupal/Core/Entity/EntityTypeManager.php on line 244
Error: Class &#039;Drupal\alinks\KeywordHtmlRouteProvider&#039; not found in Drupal\Core\Entity\EntityTypeManager->createHandlerInstance() (line 244 of /Users/gregboggs/Sites/drupal8/core/lib/Drupal/Core/Entity/EntityTypeManager.php).

**Comment by Greg-Boggs** [comment]
I went ahead and merged it, but it's not quite working yet. :)

**Comment by Greg-Boggs** [comment]
I'm working on getting the module to pass coding standards. Ran into this on the alinks settings screen on first load of a fresh site:


    Warning: Invalid argument supplied for foreach() in Drupal\Core\Render\Element\Checkboxes::valueCallback() (line 100 of core/lib/Drupal/Core/Render/Element/Checkboxes.php).

    Drupal\Core\Render\Element\Checkboxes::valueCallback(Array, , Object)
    call_user_func_array(Array, Array) (Line: 1255)
    Drupal\Core\Form\FormBuilder->handleInputElement('alinks_settings', Array, Object) (Line: 972)
    Drupal\Core\Form\FormBuilder->doBuildForm('alinks_settings', Array, Object) (Line: 1042)
    Drupal\Core\Form\FormBuilder->doBuildForm('alinks_settings', Array, Object) (Line: 1042)
    Drupal\Core\Form\FormBuilder->doBuildForm('alinks_settings', Array, Object) (Line: 555)
    Drupal\Core\Form\FormBuilder->processForm('alinks_settings', Array, Object) (Line: 314)
    Drupal\Core\Form\FormBuilder->buildForm('alinks_settings', Object) (Line: 74)
    Drupal\Core\Controller\FormController->getContentResult(Object, Object)
    call_user_func_array(Array, Array) (Line: 123)
    Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 574)
    Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
    Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
    Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
    call_user_func_array(Object, Array) (Line: 139)
    Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 62)
    Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
    Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
    Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 98)
    Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 77)
    Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
    Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 50)
    Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
    Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 628)
    Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

    Notice: Undefined index: #options in Drupal\Core\Render\Element\Checkboxes::processCheckboxes() (line 58 of core/lib/Drupal/Core/Render/Element/Checkboxes.php).

    Drupal\Core\Render\Element\Checkboxes::processCheckboxes(Array, Object, Array)
    call_user_func_array(Array, Array) (Line: 979)
    Drupal\Core\Form\FormBuilder->doBuildForm('alinks_settings', Array, Object) (Line: 1042)
    Drupal\Core\Form\FormBuilder->doBuildForm('alinks_settings', Array, Object) (Line: 1042)
    Drupal\Core\Form\FormBuilder->doBuildForm('alinks_settings', Array, Object) (Line: 555)
    Drupal\Core\Form\FormBuilder->processForm('alinks_settings', Array, Object) (Line: 314)
    Drupal\Core\Form\FormBuilder->buildForm('alinks_settings', Object) (Line: 74)
    Drupal\Core\Controller\FormController->getContentResult(Object, Object)
    call_user_func_array(Array, Array) (Line: 123)
    Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 574)
    Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
    Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
    Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
    call_user_func_array(Object, Array) (Line: 139)
    Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 62)
    Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
    Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
    Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 98)
    Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 77)
    Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
    Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 50)
    Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
    Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 628)
    Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

**Comment by Greg-Boggs** [comment]
This has been released on Drupal.org. Since we have external PHP dependencies, it current requires composer to use. We will need to come up with a workaround for this for most people to use Alinks.

**Pull request merged**
